// ============ DeliveryReviewPage.jsx ============
// One report, everything an admin needs before sending it: the QA outcome with
// the actual findings, and the invoice. Reached from the Delivery queue.
//
// Numbers on this page come from pricing_engine on the server. The QA findings
// come from the last stored QA run. Nothing here is generated by a model at
// render time.
import React, { useState, useEffect, useCallback } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { deliveryAPI } from '../api/client'

const SEVERITY_STYLE = {
    critical: { badge: 'bg-rose-500/15 text-rose-600 dark:text-rose-400', edge: 'border-l-rose-500', dot: '🔴' },
    major: { badge: 'bg-amber-500/15 text-amber-600 dark:text-amber-400', edge: 'border-l-amber-500', dot: '🟠' },
    minor: { badge: 'bg-slate-500/15 text-slate-600 dark:text-slate-400', edge: 'border-l-slate-400', dot: '⚪' },
}
const ORDER = { critical: 0, major: 1, minor: 2 }

const money = (n, currency) => {
    if (n === null || n === undefined || n === '') return '—'
    const v = Number(n)
    if (Number.isNaN(v)) return String(n)
    return `${currency || 'USD'} ${v.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

export default function DeliveryReviewPage() {
    const { reportId } = useParams()
    const navigate = useNavigate()

    const [review, setReview] = useState(null)
    const [invoice, setInvoice] = useState(null)
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState('')
    const [forbidden, setForbidden] = useState(false)
    const [sending, setSending] = useState(false)
    const [sent, setSent] = useState(null)

    const load = useCallback(async () => {
        setLoading(true); setError(''); setForbidden(false)
        try {
            const [rev, inv] = await Promise.allSettled([
                deliveryAPI.getReview(reportId),
                deliveryAPI.getInvoice(reportId),
            ])
            if (rev.status === 'fulfilled') setReview(rev.value.data)
            else if (rev.reason?.response?.status === 403) { setForbidden(true); return }
            else throw rev.reason

            // A missing invoice is not fatal — the QA half is still worth showing.
            if (inv.status === 'fulfilled') setInvoice(inv.value.data)
            else setInvoice({ _error: inv.reason?.response?.data?.detail || 'No invoice is linked to this report.' })
        } catch (e) {
            setError(e?.response?.data?.detail || e.message || 'Could not load this report.')
        } finally {
            setLoading(false)
        }
    }, [reportId])

    useEffect(() => { load() }, [load])

    const doSend = useCallback(async () => {
        if (!review?.sendable) return
        if (!window.confirm(
            `Send the report for ${review.company_name || 'this company'} to the client?\n\nThis cannot be undone.`
        )) return
        setSending(true); setError('')
        try {
            const res = await deliveryAPI.send(reportId)
            setSent(res.data)
            await load()
        } catch (e) {
            setError(e?.response?.data?.detail || e.message || 'Send failed.')
        } finally {
            setSending(false)
        }
    }, [review, reportId, load])

    if (forbidden) {
        return (
            <Shell>
                <Empty icon="🔒" title="Admins only" body="This page sends finished reports to clients." />
            </Shell>
        )
    }

    if (loading) {
        return <Shell><div className="p-10 text-center text-sm text-[var(--color-text-secondary)]">Loading…</div></Shell>
    }

    const qa = review?.qa
    const findings = [...(qa?.findings || [])].sort(
        (a, b) => (ORDER[a.severity] ?? 9) - (ORDER[b.severity] ?? 9)
    )
    const passed = qa?.verdict === 'pass'
    const inv = invoice?.invoice

    return (
        <Shell>
            {/* Header */}
            <div className="border-b border-[var(--color-border)] p-5 md:p-6 flex items-center justify-between gap-4 bg-white/70 dark:bg-white/[0.03]">
                <div className="flex items-center gap-4 min-w-0">
                    <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-indigo-500 to-purple-500 flex items-center justify-center text-white text-xl shadow-lg shadow-indigo-500/20 flex-shrink-0">📤</div>
                    <div className="min-w-0">
                        <div className="text-base md:text-lg font-black text-[var(--color-text)] truncate">
                            {review?.company_name || 'Untitled report'}
                        </div>
                        <div className="text-xs text-[var(--color-text-secondary)] mt-0.5 truncate">
                            {[review?.cr_number, review?.country, review?.analyst].filter(Boolean).join(' · ') || 'Delivery review'}
                        </div>
                    </div>
                </div>
                <button onClick={() => navigate('/admin/delivery')}
                    className="px-4 py-2 rounded-xl border border-[var(--color-border)] bg-white/70 dark:bg-white/5 text-[var(--color-text-secondary)] hover:text-primary hover:border-primary/50 transition-all text-xs font-bold flex-shrink-0">
                    ← Queue
                </button>
            </div>

            <div className="p-5 md:p-6 space-y-4">
                {error && (
                    <div className="bg-rose-50 dark:bg-rose-500/10 border border-rose-200 dark:border-rose-500/20 rounded-2xl p-4 text-rose-700 dark:text-rose-300 text-sm whitespace-pre-line">
                        ⚠️ {error}
                    </div>
                )}

                {sent && (
                    <div className="bg-emerald-50 dark:bg-emerald-500/10 border border-emerald-200 dark:border-emerald-500/20 rounded-2xl p-4 text-emerald-700 dark:text-emerald-300 text-sm">
                        ✓ Sent to <strong>{sent.to}</strong> via {sent.transport}.
                        {sent.marked_delivered === false && (
                            <div className="text-amber-600 dark:text-amber-400 mt-1">
                                The email went out, but this report could not be marked delivered — it will
                                reappear in the queue. Apply migration 011 before re-sending, or you will
                                email the client twice.
                            </div>
                        )}
                    </div>
                )}

                {review?.delivered_at && !sent && (
                    <div className="bg-slate-500/10 border border-slate-400/30 rounded-2xl p-4 text-sm text-[var(--color-text-secondary)]">
                        Already delivered {new Date(review.delivered_at).toLocaleString()}.
                    </div>
                )}

                {/* ---------- QA ---------- */}
                <Section title="Quality Review">
                    <div className={`rounded-2xl p-5 border ${qa?.verdict === null
                        ? 'bg-slate-500/10 border-slate-400/30'
                        : passed
                            ? 'bg-emerald-50 dark:bg-emerald-500/10 border-emerald-200 dark:border-emerald-500/20'
                            : 'bg-rose-50 dark:bg-rose-500/10 border-rose-200 dark:border-rose-500/20'}`}>
                        <div className="flex items-center justify-between gap-4 flex-wrap">
                            <div>
                                <div className={`text-2xl font-black ${qa?.verdict === null
                                    ? 'text-[var(--color-text-secondary)]'
                                    : passed ? 'text-emerald-600 dark:text-emerald-400' : 'text-rose-600 dark:text-rose-400'}`}>
                                    {qa?.label || 'Not checked'}
                                </div>
                                <div className="text-xs text-[var(--color-text-secondary)] mt-1">
                                    {qa?.checked_at
                                        ? `Reviewed ${new Date(qa.checked_at).toLocaleString()}`
                                        : 'This report has never been QA-checked — that is not a pass.'}
                                </div>
                            </div>
                            <div className="flex items-center gap-2 flex-wrap">
                                {qa?.critical > 0 && <Pill tone="rose" n={qa.critical} label="Critical" />}
                                {qa?.major > 0 && <Pill tone="amber" n={qa.major} label="Major" />}
                                {qa?.minor > 0 && <Pill tone="slate" n={qa.minor} label="Minor" />}
                                <button onClick={() => navigate(`/qa/${reportId}`)}
                                    className="px-4 py-2 rounded-xl bg-primary text-white font-black text-xs hover:opacity-90 transition-all">
                                    Open QA
                                </button>
                            </div>
                        </div>
                    </div>

                    {findings.length > 0 && (
                        <div className="space-y-2 mt-3">
                            {findings.map((f, i) => {
                                const style = SEVERITY_STYLE[f.severity] || SEVERITY_STYLE.minor
                                return (
                                    <div key={i} className={`bg-white/70 dark:bg-white/5 border border-[var(--color-border)] border-l-4 ${style.edge} rounded-xl p-3`}>
                                        <div className="flex items-center gap-2 min-w-0">
                                            <span>{style.dot}</span>
                                            <span className="font-mono text-[11px] font-bold text-[var(--color-text)] truncate">{f.field}</span>
                                            <span className={`px-2 py-0.5 rounded text-[9px] font-black uppercase tracking-wider ${style.badge}`}>{f.severity}</span>
                                        </div>
                                        <div className="text-xs text-[var(--color-text)] mt-1.5">{f.problem}</div>
                                        {f.evidence && <div className="text-[11px] text-[var(--color-text-secondary)] mt-0.5">{f.evidence}</div>}
                                    </div>
                                )
                            })}
                        </div>
                    )}

                    {qa?.verdict !== null && findings.length === 0 && (
                        <div className="text-xs text-[var(--color-text-secondary)] mt-3">
                            No findings recorded for this report.
                        </div>
                    )}
                </Section>

                {/* ---------- Invoice ---------- */}
                <Section title="Invoice">
                    {invoice?._error && (
                        <div className="text-xs text-[var(--color-text-secondary)]">{invoice._error}</div>
                    )}
                    {inv && (
                        <>
                            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                                <Cell label="Order" value={invoice.order_number} />
                                <Cell label="Client" value={invoice.client?.client_name} />
                                <Cell label="Service Level" value={invoice.service_level} />
                                <Cell label="Companies" value={invoice.company_count} />
                                <Cell label="Unit Price" value={money(inv.unit_price, inv.currency)} />
                                <Cell label="Subtotal" value={money(inv.subtotal, inv.currency)} />
                                <Cell label="Discount" value={money(inv.discount_amount, inv.currency)} />
                                <Cell label="Total" value={money(inv.total, inv.currency)} strong />
                            </div>
                            <div className="text-[10px] text-[var(--color-text-muted)] mt-3">
                                Computed by the pricing engine. No AI is involved in any number here.
                            </div>
                        </>
                    )}
                </Section>

                {/* ---------- Send ---------- */}
                <Section title="Send">
                    {!review?.send_enabled && (
                        <div className="text-xs text-amber-600 dark:text-amber-400 mb-3">
                            Sending is switched off. Set <code className="font-mono">DELIVERY_SEND_ENABLED=true</code> once
                            you have configured mail and sent yourself a test.
                        </div>
                    )}
                    {review?.mail && !review.mail.ready && (
                        <div className="text-xs text-[var(--color-text-secondary)] mb-3">
                            Mail is not configured. {review.mail.hint}
                        </div>
                    )}
                    {review?.mail?.ready && (
                        <div className="text-xs text-[var(--color-text-secondary)] mb-3">
                            Mail transport: <strong>{review.mail.transport}</strong>
                        </div>
                    )}

                    <button
                        onClick={doSend}
                        disabled={!review?.sendable || !review?.send_enabled || !review?.mail?.ready || sending || Boolean(review?.delivered_at)}
                        title={
                            !review?.sendable ? `Blocked: QA is "${qa?.label}". Only a passed report can be sent.`
                                : !review?.send_enabled ? 'Sending is switched off server-side.'
                                    : !review?.mail?.ready ? 'No mail transport is configured.'
                                        : review?.delivered_at ? 'Already delivered.'
                                            : 'Send this report to the client'
                        }
                        className={`w-full py-4 rounded-2xl font-black text-sm transition-all ${review?.sendable && review?.send_enabled && review?.mail?.ready && !review?.delivered_at
                            ? 'bg-gradient-to-r from-emerald-500 to-teal-500 text-white hover:shadow-xl hover:shadow-emerald-500/20'
                            : 'bg-[var(--color-surface)] text-[var(--color-text-muted)] cursor-not-allowed border border-[var(--color-border)]'}`}
                    >
                        {sending ? 'Sending…' : '📤 Send to Client'}
                    </button>
                </Section>
            </div>
        </Shell>
    )
}

function Shell({ children }) {
    return (
        <div className="min-h-[calc(100vh-96px)] w-full p-4 md:p-6">
            <div className="bg-[var(--color-surface)] dark:bg-white/5 border border-[var(--color-border)] rounded-3xl shadow-sm overflow-hidden max-w-4xl mx-auto">
                {children}
            </div>
        </div>
    )
}

function Section({ title, children }) {
    return (
        <div>
            <div className="text-[10px] font-black uppercase tracking-wider text-[var(--color-text-muted)] mb-2">{title}</div>
            {children}
        </div>
    )
}

function Pill({ tone, n, label }) {
    const tones = {
        rose: 'bg-rose-500/15 text-rose-600 dark:text-rose-400',
        amber: 'bg-amber-500/15 text-amber-600 dark:text-amber-400',
        slate: 'bg-slate-500/15 text-slate-600 dark:text-slate-400',
    }
    return <span className={`px-3 py-1 rounded-lg text-xs font-black ${tones[tone]}`}>{n} {label}</span>
}

function Cell({ label, value, strong = false }) {
    return (
        <div>
            <div className="text-[9px] font-black uppercase tracking-wider text-[var(--color-text-muted)]">{label}</div>
            <div className={`mt-0.5 break-words ${strong ? 'text-lg font-black text-[var(--color-text)]' : 'text-sm text-[var(--color-text)]'}`}>
                {value === null || value === undefined || value === '' ? '—' : String(value)}
            </div>
        </div>
    )
}

function Empty({ icon, title, body }) {
    return (
        <div className="p-10 text-center">
            <div className="text-3xl mb-3">{icon}</div>
            <div className="text-sm font-black text-[var(--color-text)]">{title}</div>
            <div className="text-xs text-[var(--color-text-secondary)] mt-1">{body}</div>
        </div>
    )
}
